# Site settings
title: Spacetron Industries Ltd
description: Pushing back the future
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Spacetron Industries Ltd
user_description: For any complaint or malfunctioning of our disruptive technologies  please write to complaints@spacetronindustries.xyz
user_title: Pushing back the future
email: complaints@spacetronindustries.xyz
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules', 'vendor', 'ruby']
